# Default values for operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: "3scale-operator"
namespace: "3scale-apimanager"

group:
  targetNamespaces:

plan:
  enabled: false
  name: "xpto"

subscription:
  channel: "threescale-2.13"
  installPlanApproval: "Manual"
  source:  "redhat-operators"
  sourceNamespace: "openshift-marketplace"
  labels: