apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ print .Values.namespace "-operator-group" }}
  namespace: {{ .Values.namespace}}
spec:
  targetNamespaces:
    - {{ .Values.namespace }}
    {{- if .Values.group.targetNamespaces }}
    {{- range .Values.group.targetNamespaces }}
    - {{ . }}
    {{- end }}
    {{- end }}