{{- if and .Values.plan (ne .Values.plan.name "") }}
apiVersion: operators.coreos.com/v1alpha1
kind: InstallPl
metadata:
  name: {{ .Values.plan.name }}
  namespace: {{ .Values.namespace }}
spec:
  approved: true
{{- end }}